### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by agentpros** [shehzadraheem/Quran-App#1]
Thanks for this beautiful app,  how to disable translation quran

**Comment by shehzadraheem** [comment]
If you want to enable/disable translation, simply add a toggle button in `Bottom Sheet` and check if it is enabled to mean translation is visible and when you disabled it then hide the translation part.

**Comment by agentpros** [comment]
Thx bro , when i try to hide the translation part in surah_detail.dart it show blank page

**Comment by shehzadraheem** [comment]
How  are you doing this?

**Comment by agentpros** [comment]
surah_detail.dart i delete line 3 //import 'package:solid_bottom_sheet/solid_bottom_sheet.dart';
also delete bottomSheet and all ListTile I am newbie on Flutter and Dart, thx for help

**Comment by agentpros** [comment]
only surah el-fatiha start with bismi lah rahman rahim , but all other surahs start without bismi lah rahman rahim

**Comment by agentpros** [comment]
how to make all surahs start with bismi lah rahman rahim ?

**Comment by shehzadraheem** [comment]
Ok, then where are you using toggle button for enabling/disabling?

**Comment by agentpros** [comment]
i dont, the most important now is to display bismi alah rahman rahim to all surah not only el fatiha

**Comment by shehzadraheem** [comment]
Then, I'm closing this
